# file: cloudbuild.yaml
substitutions:
  _REGION: "us-central1"
  _SERVICE: "venue-enricher"
  _DATASET: "rfpdata"
  _TABLE: "OUTPUT"
  _REPOSITORY: "app"
  _OPENAI_MODEL: "gpt-4o-mini"
  _BATCH_SIZE: "200"
  _CONCURRENCY: "8"
  _RUN_SA: "rfp-enricher-sa@rfp-database-464609.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build & push container
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${COMMIT_SHA}",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${COMMIT_SHA}",
      ]

  # 2) Migration: add columns (no $SQL var; inline to avoid substitution errors)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - >
        bq query --use_legacy_sql=false
        "ALTER TABLE \`${PROJECT_ID}.${_DATASET}.${_TABLE}\`
         ADD COLUMN IF NOT EXISTS city STRING,
         ADD COLUMN IF NOT EXISTS country STRING"

  # 3) Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run","deploy","${_SERVICE}",
        "--image","${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${COMMIT_SHA}",
        "--region","${_REGION}",
        "--platform","managed",
        "--allow-unauthenticated",
        "--min-instances","0",
        "--max-instances","3",
        "--cpu","1",
        "--memory","512Mi",
        "--timeout","3600",
        "--service-account","${_RUN_SA}",
        "--set-env-vars","PROJECT_ID=${PROJECT_ID},DATASET_ID=${_DATASET},TABLE_ID=${_TABLE},OPENAI_MODEL=${_OPENAI_MODEL},BATCH_SIZE=${_BATCH_SIZE},CONCURRENCY=${_CONCURRENCY}",
        "--set-secrets","OPENAI_API_KEY=OPENAI_API_KEY:latest",
      ]

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${COMMIT_SHA}"
