# file: cloudbuild.yaml
# Cloud Build pipeline: build image, migrate BigQuery columns, deploy to Cloud Run
# Configure a trigger to run this file on pushes to main.
substitutions:
  # ⚙️ Update these 3 values to your environment (once) in the Cloud Build trigger UI.
  _REGION: "us-central1"
  _SERVICE: "venue-enricher"
  _DATASET: "my_dataset"
  _TABLE: "venues"
  _REPOSITORY: "app"  # Artifact Registry repo name (create once)
  _OPENAI_MODEL: "gpt-4o-mini"
  _BATCH_SIZE: "200"
  _CONCURRENCY: "8"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build & push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${COMMIT_SHA}",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${COMMIT_SHA}",
      ]

  # 2) Migration: add city/country columns if missing
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail
        SQL="ALTER TABLE \`${PROJECT_ID}.${_DATASET}.${_TABLE}\`
             ADD COLUMN IF NOT EXISTS city STRING,
             ADD COLUMN IF NOT EXISTS country STRING"
        bq query --use_legacy_sql=false "$SQL"

  # 3) Deploy to Cloud Run (uses the OpenAI API key from Secret Manager)
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run","deploy","${_SERVICE}",
        "--image","${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${COMMIT_SHA}",
        "--region","${_REGION}",
        "--platform","managed",
        "--allow-unauthenticated",
        "--min-instances","0",
        "--max-instances","3",
        "--cpu","1",
        "--memory","512Mi",
        "--timeout","3600",
        # Runtime env:
        "--set-env-vars","PROJECT_ID=${PROJECT_ID},DATASET_ID=${_DATASET},TABLE_ID=${_TABLE},OPENAI_MODEL=${_OPENAI_MODEL},BATCH_SIZE=${_BATCH_SIZE},CONCURRENCY=${_CONCURRENCY}",
        # Secret: store a secret named OPENAI_API_KEY in Secret Manager once.
        "--set-secrets","OPENAI_API_KEY=OPENAI_API_KEY:latest",
      ]

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE}:${COMMIT_SHA}"
